### ISSUE TITLE
Some issues with chat handling

### ISSUE THREAD

**Issue by johanko** [ahmadfaizalbh/Microsoft-chatbot#2]
First off, thanks for the great framework.
To get this working in my envirnoment I had to change the request data scope(msbot/views.py line 217) from:
`https://graph.microsoft.com/.default` to `https://api.botframework.com/.default`
I also needed to utf-8 decode the json response in conversation_handler.
Responses from the bot are working, but I have some issues with the chat handler/models, maybe you could help me in the right direction.

Key error when starting new none threaded conversation with the bot:
```Traceback (most recent call last):
  File "/****/****/msbot/views.py", line 166, in __getitem__
    return self.objClass(Sender.objects.get(messengerSenderID=sender_id).messengerSenderID)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
msbot.models.DoesNotExist: Sender matching query does not exist.
```
And during handling:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/****/****/msbot/views.py", line 289, in respond_to_client
    chat.conversation[sender_id].append(message)
  File "/****/****/msbot/views.py", line 168, in __getitem__
    raise KeyError(sender_id)
```
Again, thanks

**Comment by ahmadfaizalbh** [comment]
Try running
```
python3 manage.py makemigrations
python3 manage.py migrate
```
